In [15]:
import pandas as pd

df = pd.read_csv("amazon.csv")
df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   object
 4   actual_price         1465 non-null   object
 5   discount_percentage  1465 non-null   object
 6   rating               1465 non-null   object
 7   rating_count         1463 non-null   object
 8   about_product        1465 non-null   object
 9   user_id              1465 non-null   object
 10  user_name            1465 non-null   object
 11  review_id            1465 non-null   object
 12  review_title         1465 non-null   object
 13  review_content       1465 non-null   object
 14  img_link             1465 non-null   object
 15  product_link         1465 non-null   object
dtypes: object(16)
memory usage: 183.3+ KB

In [19]:
df.isnull().sum()

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           2
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
dtype: int64

In [21]:
df.duplicated().sum()

0

In [23]:
df['discounted_price'] = (
    df['discounted_price']
    .replace('[₹,]', '', regex=True)
    .astype(float)
)

df['actual_price'] = (
    df['actual_price']
    .replace('[₹,]', '', regex=True)
    .astype(float)
)

df['discount_percentage'] = (
    df['discount_percentage']
    .str.replace('%', '')
    .astype(float)
)

In [25]:
df['rating_count'] = (
    df['rating_count']
    .replace(',', '', regex=True)
    .fillna(0)
    .astype(int)
)

In [27]:
# Clean rating column
df['rating'] = pd.to_numeric(df['rating'], errors='coerce')

# Fill missing/invalid ratings with median
df['rating'] = df['rating'].fillna(df['rating'].median())

In [29]:
df = df.drop_duplicates()

In [31]:
df.isnull().sum()

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           0
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
dtype: int64

In [33]:
# create a new column price_gap 
df['price_gap'] = df['actual_price'] - df['discounted_price']

In [35]:
df[['product_id','price_gap']].head(10)

   product_id  price_gap
0  B07JW9H4J1     700.00
1  B098NS6PVG     150.00
2  B096MSW6CT    1700.00
3  B08HDJ86NZ     370.00
4  B08CF3B7N1     245.00
5  B08Y1TFSP6     851.00
6  B08WRWPM22     322.37
7  B08DDRGWTJ      70.00
8  B008IFXQFU     500.00
9  B082LZGK39     100.00

In [37]:
#create a new column rating_segment
df['rating_segment'] = pd.cut(
    df['rating'],
    bins=[0,3,4,5],
    labels=['Poor','Average','Excellent']
)

In [39]:
df[['product_id','rating_segment']].head(10)

   product_id rating_segment
0  B07JW9H4J1      Excellent
1  B098NS6PVG        Average
2  B096MSW6CT        Average
3  B08HDJ86NZ      Excellent
4  B08CF3B7N1      Excellent
5  B08Y1TFSP6        Average
6  B08WRWPM22      Excellent
7  B08DDRGWTJ      Excellent
8  B008IFXQFU      Excellent
9  B082LZGK39        Average

In [41]:
#create a new column discount_bucket 
df['discount_bucket'] = pd.cut(
    df['discount_percentage'],
    bins=[0,20,40,60,100],
    labels=['Low','Medium','High','Very High']
)

In [43]:
df[['discount_percentage','discount_bucket']].head(10)

   discount_percentage discount_bucket
0                 64.0       Very High
1                 43.0            High
2                 90.0       Very High
3                 53.0            High
4                 61.0       Very High
5                 85.0       Very High
6                 65.0       Very High
7                 23.0          Medium
8                 50.0            High
9                 33.0          Medium

In [62]:
#create a new column revenue_score
import numpy as np

df['revenue_score'] = (
    df['discounted_price'] *
    np.log1p(df['rating_count']) *
    df['rating']
)

In [64]:
df[['product_id','revenue_score']].head(10)

   product_id  revenue_score
0  B07JW9H4J1   16920.546397
1  B098NS6PVG    8510.697691
2  B096MSW6CT    6968.044818
3  B08HDJ86NZ   15828.401441
4  B08CF3B7N1    6296.872157
5  B08Y1TFSP6    5881.602460
6  B08WRWPM22    6972.670558
7  B08DDRGWTJ   10164.656880
8  B008IFXQFU   25357.083263
9  B082LZGK39    8510.697691

In [66]:
df.columns

Index(['product_id', 'product_name', 'category', 'discounted_price',
       'actual_price', 'discount_percentage', 'rating', 'rating_count',
       'about_product', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content', 'img_link', 'product_link', 'price_gap',
       'rating_segment', 'discount_bucket', 'revenue_score'],
      dtype='object')

In [68]:
#Connecting Python script to MySQL

!pip install pymysql sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymysql in c:\users\kiit\appdata\roaming\python\python312\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)

In [82]:
from sqlalchemy import create_engine
import pandas as pd

username = "root"
password = "mysql"
host = "localhost"
port = "3306"
database = "amazon_product_intelligence"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

In [86]:
df.to_sql(
    "amazon_products",
    con=engine,
    if_exists="replace",
    index=False
)

1465

In [88]:
sample = pd.read_sql(
    "SELECT * FROM amazon_products LIMIT 5;",
    engine
)

print(sample)

   product_id                                       product_name  \
0  B07JW9H4J1  Wayona Nylon Braided USB to Lightning Fast Cha...
1  B098NS6PVG  Ambrane Unbreakable 60W / 3A Fast Charging 1.5...
2  B096MSW6CT  Sounce Fast Phone Charging Cable & Data Sync U...
3  B08HDJ86NZ  boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...
4  B08CF3B7N1  Portronics Konnect L 1.2M Fast Charging 3A 8 P...

                                            category  discounted_price  \
0  Computers&Accessories|Accessories&Peripherals|...             399.0
1  Computers&Accessories|Accessories&Peripherals|...             199.0
2  Computers&Accessories|Accessories&Peripherals|...             199.0
3  Computers&Accessories|Accessories&Peripherals|...             329.0
4  Computers&Accessories|Accessories&Peripherals|...             154.0

   actual_price  discount_percentage  rating  rating_count  \
0        1099.0                 64.0     4.2         24269
1         349.0                 43.0     4.0         43994
2        1899.0                 90.0     3.9          7928
3         699.0                 53.0     4.2         94363
4         399.0                 61.0     4.2         16905

                                       about_product  \
0  High Compatibility : Compatible With iPhone 12...
1  Compatible with all Type C enabled devices, be...
2  【 Fast Charger& Data Sync】-With built-in safet...
3  The boAt Deuce USB 300 2 in 1 cable is compati...
4  [CHARGE & SYNC FUNCTION]- This cable comes wit...

                                             user_id  \
0  AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...
1  AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...
2  AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...
3  AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...
4  AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...

                                           user_name  \
0  Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...
1  ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...
2  Kunal,Himanshu,viswanath,sai niharka,saqib mal...
3  Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...
4  rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...

                                           review_id  \
0  R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...
1  RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...
2  R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...
3  R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...
4  R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...

                                        review_title  \
0  Satisfied,Charging is really fast,Value for mo...
1  A Good Braided Cable for Your Type C Device,Go...
2  Good speed for earlier versions,Good Product,W...
3  Good product,Good one,Nice,Really nice product...
4  As good as original,Decent,Good one for second...

                                      review_content  \
0  Looks durable Charging is fine tooNo complains...
1  I ordered this cable to connect my phone to An...
2  Not quite durable and sturdy,https://m.media-a...
3  Good product,long wire,Charges good,Nice,I bou...
4  Bought this instead of original apple, does th...

                                            img_link  \
0  https://m.media-amazon.com/images/W/WEBP_40237...
1  https://m.media-amazon.com/images/W/WEBP_40237...
2  https://m.media-amazon.com/images/W/WEBP_40237...
3  https://m.media-amazon.com/images/I/41V5FtEWPk...
4  https://m.media-amazon.com/images/W/WEBP_40237...

                                        product_link  price_gap  \
0  https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...      700.0
1  https://www.amazon.in/Ambrane-Unbreakable-Char...      150.0
2  https://www.amazon.in/Sounce-iPhone-Charging-C...     1700.0
3  https://www.amazon.in/Deuce-300-Resistant-Tang...      370.0
4  https://www.amazon.in/Portronics-Konnect-POR-1...      245.0

  rating_segment discount_bucket  revenue_score
0      Excellent       Very High   16920.546397
1        Average            High    8510.697691
2        Average       Very High    6968.044818
3      Excellent            High   15828.401441
4      Excellent       Very High    6296.872157

In [84]:
df['revenue_score'].describe()

count    1.465000e+03
mean     1.127727e+05
std      2.616031e+05
min      0.000000e+00
25%      9.998326e+03
50%      2.639946e+04
75%      7.257268e+04
max      3.184902e+06
Name: revenue_score, dtype: float64